package com.wordnik.client.model



case class Advisor (
  company: String,
  address: String,
  city: String,
  state: String,
  zip: String,
  first_name: String,
  last_name: String,
  reg_number: String,
  account_type: String,
  advisor_employees: String,
  other_services_types: String,
  other_compensation: String,
  performance_audited: String,
  about: String,
  twitter_handle: String,
  profile_picture: String,
  logo: String,
  linkedin: String,
  website: String,
  adv_brochure: String,
  plan: String,
  consultation_reminder: String,
  referral_reminder: String,
  weekly_email_blast: String,
  disclosure: String,
  external_options: String,
  email_report_blast: String,
  email_blast: String,
  twitter_blast: String,
  linkedin_blast: String,
  facebook_blast: String,
  compliance_bcc_email_address: String,
  dashboard_url: String,
  api_key: String,
  id: String,
  name: String,
  tag: String
)
