#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class Member:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            
            '_id': 'str',
            
            
            'email': 'str',
            
            
            'first_name': 'str',
            
            
            'last_name': 'str',
            
            
            'phone': 'str',
            
            
            'address': 'str',
            
            
            'city': 'str',
            
            
            'state': 'str',
            
            
            'zip': 'str',
            
            
            'gender': 'str',
            
            
            'age': 'str',
            
            
            'education': 'str',
            
            
            'high_net_worth': 'bool',
            
            
            'home_market_value': 'str',
            
            
            'home_owner_status': 'str',
            
            
            'household_income': 'str',
            
            
            'marital_status': 'str',
            
            
            'occupation': 'str',
            
            
            'hometown': 'str',
            
            
            'family': 'str',
            
            
            'tags': 'str',
            
            
            'message': 'str',
            
            
            'location': 'str',
            
            
            'picture_url': 'str',
            
            
            'profile_url': 'str',
            
            
            'estimated_location': 'str',
            
            
            'estimated_zip': 'str',
            
            
            'register_ip_addr': 'str',
            
            
            'data_estimated': 'bool',
            
            
            'genuine_email': 'bool'
            
        }


        
        #Id of object
        
        self._id = None # str
        
        #Email Address
        
        self.email = None # str
        
        #First Name
        
        self.first_name = None # str
        
        #Last Name
        
        self.last_name = None # str
        
        #Phone Number
        
        self.phone = None # str
        
        #Postal Address
        
        self.address = None # str
        
        #Postal City
        
        self.city = None # str
        
        #Postal State
        
        self.state = None # str
        
        #Postal Zipcode
        
        self.zip = None # str
        
        #Gender
        
        self.gender = None # str
        
        #Age Range
        
        self.age = None # str
        
        #Education
        
        self.education = None # str
        
        #High Net Worth
        
        self.high_net_worth = None # bool
        
        #Home Market Value
        
        self.home_market_value = None # str
        
        #Home Owner Status
        
        self.home_owner_status = None # str
        
        #Household Income
        
        self.household_income = None # str
        
        #Marital Status
        
        self.marital_status = None # str
        
        #Occupation
        
        self.occupation = None # str
        
        #Hometown
        
        self.hometown = None # str
        
        #Family Members
        
        self.family = None # str
        
        #Tags
        
        self.tags = None # str
        
        #Message and notes
        
        self.message = None # str
        
        #Location
        
        self.location = None # str
        
        #Picture URL
        
        self.picture_url = None # str
        
        #Social Profile URL
        
        self.profile_url = None # str
        
        #Estimated Location
        
        self.estimated_location = None # str
        
        #Estimated Zipcode
        
        self.estimated_zip = None # str
        
        #First recorded IP Address
        
        self.register_ip_addr = None # str
        
        #Data Estimated
        
        self.data_estimated = None # bool
        
        #Genuine Email address
        
        self.genuine_email = None # bool
        
