<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class SourcesApi {

	function __construct($apiClient) {
	  $this->apiClient = $apiClient;
	}

  
	/**
	 * index
   *
	 * Read a list of sources
   * vestorly-auth, string: Authentication token (required)
   * * ids, string: Return sources with list of IDs provided (required)
   * 
	 * @return void
	 */

   public function index($vestorly-auth, $ids) {

  		// parse inputs
  		$resourcePath = "api/sources.json";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();
      $formParams = array();
      $headerParams['Accept'] = '';
      $headerParams['Content-Type'] = '';

      // query params
      if($vestorly-auth !== null) {
  		  $queryParams['vestorly-auth'] = $this->apiClient->toQueryValue($vestorly-auth);
  		}// query params
      if($ids !== null) {
  		  $queryParams['ids'] = $this->apiClient->toQueryValue($ids);
  		}
      
      
      
      

      $body = $body ?: $formParams;

      if (strpos($headerParams['Content-Type'], "application/x-www-form-urlencoded") > -1) {
        $body = http_build_query($body);
      }

  		// make the API Call
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);

      if(! $response) {
        return null;
      }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'void');
  		return $responseObject;
  }
  
	/**
	 * show
   *
	 * Read a specific source
   * vestorly-auth, string: Authentication token (required)
   * * id, string: Id of source (required)
   * 
	 * @return void
	 */

   public function show($vestorly-auth, $id) {

  		// parse inputs
  		$resourcePath = "api/sources/{id}.json";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();
      $formParams = array();
      $headerParams['Accept'] = '';
      $headerParams['Content-Type'] = '';

      // query params
      if($vestorly-auth !== null) {
  		  $queryParams['vestorly-auth'] = $this->apiClient->toQueryValue($vestorly-auth);
  		}
      
      // path params
      if($id !== null) {
  			$resourcePath = str_replace("{" . "id" . "}",
  			                            $this->apiClient->toPathValue($id), $resourcePath);
  		}
      
      

      $body = $body ?: $formParams;

      if (strpos($headerParams['Content-Type'], "application/x-www-form-urlencoded") > -1) {
        $body = http_build_query($body);
      }

  		// make the API Call
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);

      if(! $response) {
        return null;
      }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'void');
  		return $responseObject;
  }
  
	/**
	 * update
   *
	 * Create a source
   * id, string: Id of g (required)
   * * source, string: JSON block of source data (required)
   * 
	 * @return void
	 */

   public function update($id, $source) {

  		// parse inputs
  		$resourcePath = "api/sources/{id}.json";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "PUT";
      $queryParams = array();
      $headerParams = array();
      $formParams = array();
      $headerParams['Accept'] = '';
      $headerParams['Content-Type'] = '';

      
      
      // path params
      if($id !== null) {
  			$resourcePath = str_replace("{" . "id" . "}",
  			                            $this->apiClient->toPathValue($id), $resourcePath);
  		}
      
      if ($source !== null) {
        $formParams[source] = $source;
      }
      

      $body = $body ?: $formParams;

      if (strpos($headerParams['Content-Type'], "application/x-www-form-urlencoded") > -1) {
        $body = http_build_query($body);
      }

  		// make the API Call
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);

      if(! $response) {
        return null;
      }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'void');
  		return $responseObject;
  }
  

}
