<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace Vestorly\models;

use \ArrayAccess;

class OrgSetting implements ArrayAccess {
  static $swaggerTypes = array(
      '_id' => 'string',
      'is_default' => 'boolean',
      'name' => 'string',
      'email_theme_name' => 'string',
      'company_address' => 'string',
      'company_contact_email' => 'string',
      'site_url' => 'string',
      'company_homepage_url' => 'string',
      'privacy_policy_url' => 'string',
      'terms_and_conditions_url' => 'string'
  );

  static $attributeMap = array(
      '_id' => '_id',
      'is_default' => 'is_default',
      'name' => 'name',
      'email_theme_name' => 'email_theme_name',
      'company_address' => 'company_address',
      'company_contact_email' => 'company_contact_email',
      'site_url' => 'site_url',
      'company_homepage_url' => 'company_homepage_url',
      'privacy_policy_url' => 'privacy_policy_url',
      'terms_and_conditions_url' => 'terms_and_conditions_url'
  );

  
  public $_id; /* string */
  public $is_default; /* boolean */
  public $name; /* string */
  public $email_theme_name; /* string */
  public $company_address; /* string */
  public $company_contact_email; /* string */
  public $site_url; /* string */
  public $company_homepage_url; /* string */
  public $privacy_policy_url; /* string */
  public $terms_and_conditions_url; /* string */

  public function __construct(array $data = null) {
    $this->_id = $data["_id"];
    $this->is_default = $data["is_default"];
    $this->name = $data["name"];
    $this->email_theme_name = $data["email_theme_name"];
    $this->company_address = $data["company_address"];
    $this->company_contact_email = $data["company_contact_email"];
    $this->site_url = $data["site_url"];
    $this->company_homepage_url = $data["company_homepage_url"];
    $this->privacy_policy_url = $data["privacy_policy_url"];
    $this->terms_and_conditions_url = $data["terms_and_conditions_url"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
