<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace Vestorly\models;

use \ArrayAccess;

class PostInput implements ArrayAccess {
  static $swaggerTypes = array(
      'title' => 'string',
      'post_date' => 'string',
      'body' => 'string',
      'comment' => 'string',
      'client_only' => 'boolean',
      'attachment' => 'string',
      'video' => 'string',
      'img' => 'string',
      'image_url' => 'string',
      'img_compressed' => 'boolean',
      'img_changed' => 'boolean',
      'topic' => 'string'
  );

  static $attributeMap = array(
      'title' => 'title',
      'post_date' => 'post_date',
      'body' => 'body',
      'comment' => 'comment',
      'client_only' => 'client_only',
      'attachment' => 'attachment',
      'video' => 'video',
      'img' => 'img',
      'image_url' => 'image_url',
      'img_compressed' => 'img_compressed',
      'img_changed' => 'img_changed',
      'topic' => 'topic'
  );

  
  public $title; /* string */
  public $post_date; /* string */
  public $body; /* string */
  public $comment; /* string */
  public $client_only; /* boolean */
  public $attachment; /* string */
  public $video; /* string */
  public $img; /* string */
  public $image_url; /* string */
  public $img_compressed; /* boolean */
  public $img_changed; /* boolean */
  public $topic; /* string */

  public function __construct(array $data = null) {
    $this->title = $data["title"];
    $this->post_date = $data["post_date"];
    $this->body = $data["body"];
    $this->comment = $data["comment"];
    $this->client_only = $data["client_only"];
    $this->attachment = $data["attachment"];
    $this->video = $data["video"];
    $this->img = $data["img"];
    $this->image_url = $data["image_url"];
    $this->img_compressed = $data["img_compressed"];
    $this->img_changed = $data["img_changed"];
    $this->topic = $data["topic"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
