#!/usr/bin/env python
# coding: utf-8

"""
SessionsApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
from __future__ import absolute_import

import sys
import os

# python 2 and python 3 compatibility library
from six import iteritems

from ..util import remove_none

from ..swagger import ApiClient

class SessionsApi(object):

    def __init__(self, api_client):
        self.api_client = api_client
    
    def login(self, username, password, **kwargs):
        """
        
        Login To Vestorly Platform

        :param str username: Username in the vestorly platform (required)
        :param str password: Password in Vestorly Platform (required)
        
        :return: Session
        """
        
        # verify the required parameter 'username' is set
        if username is None:
            raise ValueError("Missing the required parameter `username` when calling `login`")
        
        # verify the required parameter 'password' is set
        if password is None:
            raise ValueError("Missing the required parameter `password` when calling `login`")
        
        all_params = ['username', 'password']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method login" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/sessions'.replace('{format}', 'json')
        method = 'POST'

        path_params = remove_none(dict())
        query_params = remove_none(dict(username=params.get('username'), password=params.get('password')))
        header_params = remove_none(dict())
        form_params = remove_none(dict())
        files = remove_none(dict())
        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = ApiClient.select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = ApiClient.select_header_content_type(['application/x-www-form-urlencoded'])

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response='Session')
        
        return response
        
    def logout(self, vestorly_auth, id, **kwargs):
        """
        
        Logout of the vestorly platform

        :param str vestorly_auth: Authenication token (required)
        :param str id: ID of pet to session (required)
        
        :return: SessionLogoutResponse
        """
        
        # verify the required parameter 'vestorly_auth' is set
        if vestorly_auth is None:
            raise ValueError("Missing the required parameter `vestorly_auth` when calling `logout`")
        
        # verify the required parameter 'id' is set
        if id is None:
            raise ValueError("Missing the required parameter `id` when calling `logout`")
        
        all_params = ['vestorly_auth', 'id']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method logout" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/sessions/{id}'.replace('{format}', 'json')
        method = 'DELETE'

        path_params = remove_none(dict(id=params.get('id')))
        query_params = remove_none(dict(vestorly_auth=params.get('vestorly_auth')))
        header_params = remove_none(dict())
        form_params = remove_none(dict())
        files = remove_none(dict())
        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = ApiClient.select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = ApiClient.select_header_content_type([])

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response='SessionLogoutResponse')
        
        return response
        









