<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

class Article {
  static $swaggerTypes = array(
      '_id' => 'string',
      'url' => 'string',
      'title' => 'string',
      'open_calais_topics' => 'string',
      'open_calais_keywords' => 'string',
      'categories' => 'string',
      'summary' => 'string',
      'unparsed_html' => 'string',
      'parsed_html' => 'string',
      'content' => 'string',
      'vestorly_topics' => 'string',
      'override_topic' => 'string',
      'published_at' => 'datetime',
      'original_image_url' => 'string',
      'small_image_url' => 'string',
      'large_image_url' => 'string',
      'img' => 'string',
      'webpage_mobile_image_url' => 'string',
      'webpage_tablet_image_url' => 'string',
      'rss_feed_url' => 'string',
      'rss_feed_category' => 'string',
      'rss_feed_logo_url' => 'string',
      'needs_sanitize' => 'boolean',
      'is_responsive' => 'boolean',
      'is_proxy_needed' => 'boolean',
      'is_mobile_proxy_needed' => 'boolean',
      'is_working_url' => 'boolean'
    );

  
  /**
  * Id of object
  */
  public $_id; /* string */
  /**
  * URL of the article
  */
  public $url; /* string */
  /**
  * Title of the article
  */
  public $title; /* string */
  /**
  * Open calcais optics
  */
  public $open_calais_topics; /* string */
  /**
  * Open calais keywords
  */
  public $open_calais_keywords; /* string */
  /**
  * Categories of article
  */
  public $categories; /* string */
  /**
  * Summary of article
  */
  public $summary; /* string */
  /**
  * Unparsed HTML
  */
  public $unparsed_html; /* string */
  /**
  * Parsed HTML
  */
  public $parsed_html; /* string */
  /**
  * Content of article
  */
  public $content; /* string */
  /**
  * Vestorly topics
  */
  public $vestorly_topics; /* string */
  /**
  * Override topics
  */
  public $override_topic; /* string */
  /**
  * Article published at time
  */
  public $published_at; /* datetime */
  /**
  * Original image url
  */
  public $original_image_url; /* string */
  /**
  * Small image url
  */
  public $small_image_url; /* string */
  /**
  * Large image url
  */
  public $large_image_url; /* string */
  /**
  * Image
  */
  public $img; /* string */
  /**
  * Webpage mobile url
  */
  public $webpage_mobile_image_url; /* string */
  /**
  * Webpage tablet url
  */
  public $webpage_tablet_image_url; /* string */
  /**
  * Article URL
  */
  public $rss_feed_url; /* string */
  /**
  * Article category
  */
  public $rss_feed_category; /* string */
  /**
  * Article logo
  */
  public $rss_feed_logo_url; /* string */
  /**
  * Does this article need sanitizing?
  */
  public $needs_sanitize; /* boolean */
  /**
  * Is this article responsive
  */
  public $is_responsive; /* boolean */
  /**
  * Is a proxy used for this article
  */
  public $is_proxy_needed; /* boolean */
  /**
  * Is mobile proxying needed
  */
  public $is_mobile_proxy_needed; /* boolean */
  /**
  * Is working url?
  */
  public $is_working_url; /* boolean */
}
