<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

class Event {
  static $swaggerTypes = array(
      '_id' => 'string',
      'type' => 'symbol',
      'referrer' => 'string',
      'original_url' => 'string',
      'originator_email' => 'string',
      'subject_email' => 'string',
      'advisor_email' => 'string',
      'originator_group_name' => 'string',
      'newsletter' => 'string'
    );

  
  /**
  * Id of object
  */
  public $_id; /* string */
  /**
  * Type of the event
  */
  public $type; /* symbol */
  /**
  * Event referrer
  */
  public $referrer; /* string */
  /**
  * Originator URL
  */
  public $original_url; /* string */
  /**
  * Originator email
  */
  public $originator_email; /* string */
  /**
  * Subject email
  */
  public $subject_email; /* string */
  /**
  * Advisor email
  */
  public $advisor_email; /* string */
  /**
  * Original group name
  */
  public $originator_group_name; /* string */
  /**
  * Newsletter
  */
  public $newsletter; /* string */
}
