package io.swagger.client.model




case class Member (
  _id: String,
  email: String,
  first_name: String,
  last_name: String,
  phone: String,
  address: String,
  city: String,
  state: String,
  zip: String,
  gender: String,
  interest_consultation: String,
  interest_in_new_advisor: String,
  assets: String,
  age: String,
  data_estimated: Boolean,
  education: String,
  high_net_worth: Boolean,
  home_market_value: String,
  home_owner_status: String,
  household_income: String,
  marital_status: String,
  occupation: String,
  hometown: String,
  family: String,
  tags: List[String],
  subscribed_group_ids: List[String],
  unsubscribed: Boolean,
  unsubscribed_date: Boolean,
  user_type: String,
  signed_up_with: String,
  message: String,
  location: String,
  picture_url: String,
  profile_url: String,
  estimated_location: String,
  estimated_zip: String,
  register_ip_addr: String,
  genuine_email: Boolean,
  last_active_date: String,
  is_client: Boolean,
  is_hidden: Boolean,
  invited_on: String,
  invited_by: String,
  portfolio_size: String)
  
