package io.swagger.client.model




case class NewsletterSetting (
  _id: String,
  email_day_of_week: Integer,
  email_hour: Integer,
  email_status: String,
  facebook_active_wall: String,
  facebook_day_of_week: Integer,
  facebook_hour: Integer,
  facebook_status: String,
  linkedin_active_wall: String,
  linkedin_day_of_week: Integer,
  linkedin_hour: Integer,
  linkedin_status: String,
  social_title: String,
  social_subtitle: String,
  social_description: String,
  twitter_day_of_week: Integer,
  twitter_hour: Integer,
  twitter_status: String,
  social_posting_text: String,
  newsletter_type: String,
  group_id: String,
  montage_enabled: Boolean,
  montage_title: String,
  montage_facebook_image_url: String,
  montage_linkedin_image_url: String,
  montage_twitter_image_url: String,
  newsletter_ids: List[String],
  primary_email_font: String,
  footer_email_font: String,
  email_accent_color: String,
  render_version: String,
  header_image_url: String,
  header_background_color: String,
  banner_color: String,
  title_color: String,
  footer_html: String,
  intro_text: String,
  footer_image_url: String,
  subject: String,
  salutation_text: String,
  body_html: String)
  
