<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace VestorlyClient\models;

use \ArrayAccess;

class NewsletterInput implements ArrayAccess {
  static $swaggerTypes = array(
      'is_sent' => 'boolean',
      'is_default' => 'boolean',
      'click_count' => 'int',
      'unique_click_count' => 'int',
      'total_click_count' => 'int'
  );

  static $attributeMap = array(
      'is_sent' => 'is_sent',
      'is_default' => 'is_default',
      'click_count' => 'click_count',
      'unique_click_count' => 'unique_click_count',
      'total_click_count' => 'total_click_count'
  );

  
  public $is_sent; /* boolean */
  public $is_default; /* boolean */
  public $click_count; /* int */
  public $unique_click_count; /* int */
  public $total_click_count; /* int */

  public function __construct(array $data = null) {
    $this->is_sent = $data["is_sent"];
    $this->is_default = $data["is_default"];
    $this->click_count = $data["click_count"];
    $this->unique_click_count = $data["unique_click_count"];
    $this->total_click_count = $data["total_click_count"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
