<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace VestorlyClient\models;

use \ArrayAccess;

class TruncatedMember implements ArrayAccess {
  static $swaggerTypes = array(
      '_id' => 'string',
      'first_name' => 'string',
      'last_name' => 'string',
      'email' => 'string',
      'picture_url' => 'string',
      'added_on' => 'string'
  );

  static $attributeMap = array(
      '_id' => '_id',
      'first_name' => 'first_name',
      'last_name' => 'last_name',
      'email' => 'email',
      'picture_url' => 'picture_url',
      'added_on' => 'added_on'
  );

  
  public $_id; /* string */
  public $first_name; /* string */
  public $last_name; /* string */
  public $email; /* string */
  public $picture_url; /* string */
  public $added_on; /* string */

  public function __construct(array $data = null) {
    $this->_id = $data["_id"];
    $this->first_name = $data["first_name"];
    $this->last_name = $data["last_name"];
    $this->email = $data["email"];
    $this->picture_url = $data["picture_url"];
    $this->added_on = $data["added_on"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
