#!/usr/bin/env python
"""
AdvisorsApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class AdvisorsApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def create(self, **kwargs):
        """Create an advisor

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            advisor, str: JSON block of advisor data (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'advisor']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method create" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/advisors.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        

        

        

        
        if ('advisor' in params):
            formParams['advisor'] = params['advisor']
        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def show(self, **kwargs):
        """Read a specific advisor

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            id, str: Id of advisor (required)
            
            
            filter_by, str: Filtered by [signups/page_views] (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'id', 'filter_by']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method show" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/advisors/{id}.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        
        if ('filter_by' in params):
            queryParams['filter_by'] = self.apiClient.toPathValue(params['filter_by'])
        

        

        
        if ('id' in params):
            replacement = str(self.apiClient.toPathValue(params['id']))
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def update(self, **kwargs):
        """Update a advisor

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            id, str: Id of advisor (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'id']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method update" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/advisors/{id}.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        

        

        
        if ('id' in params):
            replacement = str(self.apiClient.toPathValue(params['id']))
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    


