#!/usr/bin/env python
"""
PostsApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class PostsApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def index(self, **kwargs):
        """Read a list of posts

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            filter_by, str: Supports [all/published/unpublished/features/vestorly/newsletter] (required)
            
            
            filter_by_group_id, str: Filter by group id (required)
            
            
            filter_by_newsletter_id, str: Filter by newsletter (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'filter_by', 'filter_by_group_id', 'filter_by_newsletter_id']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method index" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/advisors/{advisor_id}/posts.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        
        if ('filter_by' in params):
            queryParams['filter_by'] = self.apiClient.toPathValue(params['filter_by'])
        
        if ('filter_by_group_id' in params):
            queryParams['filter_by_group_id'] = self.apiClient.toPathValue(params['filter_by_group_id'])
        
        if ('filter_by_newsletter_id' in params):
            queryParams['filter_by_newsletter_id'] = self.apiClient.toPathValue(params['filter_by_newsletter_id'])
        

        

        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def create(self, **kwargs):
        """Create an post

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            advisor_id, str: Id of advisor (required)
            
            
            post, str: JSON block of post data (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'advisor_id', 'post']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method create" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/advisors/{advisor_id}/posts.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        

        

        
        if ('advisor_id' in params):
            replacement = str(self.apiClient.toPathValue(params['advisor_id']))
            resourcePath = resourcePath.replace('{' + 'advisor_id' + '}',
                                                replacement)
        

        
        if ('post' in params):
            formParams['post'] = params['post']
        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def show(self, **kwargs):
        """Read a specific post

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            id, str: Id of post (required)
            
            
            advisor_id, str: Id of advisor (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'id', 'advisor_id']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method show" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/advisors/{advisor_id}/posts/{id}.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        

        

        
        if ('id' in params):
            replacement = str(self.apiClient.toPathValue(params['id']))
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        
        if ('advisor_id' in params):
            replacement = str(self.apiClient.toPathValue(params['advisor_id']))
            resourcePath = resourcePath.replace('{' + 'advisor_id' + '}',
                                                replacement)
        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def update(self, **kwargs):
        """Update a post

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            id, str: Id of post (required)
            
            
            advisor_id, str: Id of advisor (required)
            
            
            post, str: JSON block of post data (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'id', 'advisor_id', 'post']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method update" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/advisors/{advisor_id}/posts/{id}.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        

        

        
        if ('id' in params):
            replacement = str(self.apiClient.toPathValue(params['id']))
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        
        if ('advisor_id' in params):
            replacement = str(self.apiClient.toPathValue(params['advisor_id']))
            resourcePath = resourcePath.replace('{' + 'advisor_id' + '}',
                                                replacement)
        

        
        if ('post' in params):
            formParams['post'] = params['post']
        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def destroy(self, **kwargs):
        """Deletes a post

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            id, str: Id of advisor (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'id']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method destroy" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/advisors/{advisor_id}/posts/{id}.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        

        

        
        if ('id' in params):
            replacement = str(self.apiClient.toPathValue(params['id']))
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    


