<?php
/**
 *  Copyright 2014 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class MembersApi {

	function __construct($apiClient) {
	  $this->apiClient = $apiClient;
	}

  
	/**
	 * index
   *
	 * Read member lead data
   * vestorly-auth, string: Authentication token (required)
   * * advisor_id, string: Id of Advisor (required)
   * * search, string: Fuzzy search by name (required)
   * * sorted_by, string: Sort by: first_name, last_name, content_views, shares, posts_read, signed_up, last_active (required)
   * * sorted_order, string: Sort order: asc, desc (required)
   * 
	 * @return void
	 */

   public function index($vestorly-auth, $advisor_id, $search, $sorted_by, $sorted_order) {

  		// parse inputs
  		$resourcePath = "api/advisors/{advisor_id}/members.json";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();
      $headerParams['Accept'] = '';
      $headerParams['Content-Type'] = '';

      // query params
      if($vestorly-auth != null) {
  		  $queryParams['vestorly-auth'] = $this->apiClient->toQueryValue($vestorly-auth);
  		}// query params
      if($search != null) {
  		  $queryParams['search'] = $this->apiClient->toQueryValue($search);
  		}// query params
      if($sorted_by != null) {
  		  $queryParams['sorted_by'] = $this->apiClient->toQueryValue($sorted_by);
  		}// query params
      if($sorted_order != null) {
  		  $queryParams['sorted_order'] = $this->apiClient->toQueryValue($sorted_order);
  		}
      
      // path params
      if($advisor_id != null) {
  			$resourcePath = str_replace("{" . "advisor_id" . "}",
  			                            $this->apiClient->toPathValue($advisor_id), $resourcePath);
  		}
      

  		// make the API Call
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);

      if(! $response) {
        return null;
      }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'void');
  		return $responseObject;
  }
  
	/**
	 * create
   *
	 * Create a member
   * vestorly-auth, string: Authentication token (required)
   * * advisor_id, string: Id of advisor (required)
   * * member, string: JSON block of member data (required)
   * 
	 * @return void
	 */

   public function create($vestorly-auth, $advisor_id, $member) {

  		// parse inputs
  		$resourcePath = "api/advisors/{advisor_id}/members.json";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "POST";
      $queryParams = array();
      $headerParams = array();
      $headerParams['Accept'] = '';
      $headerParams['Content-Type'] = '';

      // query params
      if($vestorly-auth != null) {
  		  $queryParams['vestorly-auth'] = $this->apiClient->toQueryValue($vestorly-auth);
  		}
      
      // path params
      if($advisor_id != null) {
  			$resourcePath = str_replace("{" . "advisor_id" . "}",
  			                            $this->apiClient->toPathValue($advisor_id), $resourcePath);
  		}
      

  		// make the API Call
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);

      if(! $response) {
        return null;
      }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'void');
  		return $responseObject;
  }
  
	/**
	 * show
   *
	 * Read a specific member
   * vestorly-auth, string: Authentication token (required)
   * * advisor_id, string: Id of advisor (required)
   * * id, string: Id of member (required)
   * 
	 * @return void
	 */

   public function show($vestorly-auth, $advisor_id, $id) {

  		// parse inputs
  		$resourcePath = "api/advisors/{advisor_id}/members/{id}.json";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();
      $headerParams['Accept'] = '';
      $headerParams['Content-Type'] = '';

      // query params
      if($vestorly-auth != null) {
  		  $queryParams['vestorly-auth'] = $this->apiClient->toQueryValue($vestorly-auth);
  		}
      
      // path params
      if($advisor_id != null) {
  			$resourcePath = str_replace("{" . "advisor_id" . "}",
  			                            $this->apiClient->toPathValue($advisor_id), $resourcePath);
  		}// path params
      if($id != null) {
  			$resourcePath = str_replace("{" . "id" . "}",
  			                            $this->apiClient->toPathValue($id), $resourcePath);
  		}
      

  		// make the API Call
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);

      if(! $response) {
        return null;
      }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'void');
  		return $responseObject;
  }
  
	/**
	 * update
   *
	 * Update a member
   * vestorly-auth, string: Authentication token (required)
   * * advisor_id, string: Id of advisor (required)
   * * id, string: Id of member (required)
   * * member, string: JSON block of member data (required)
   * 
	 * @return void
	 */

   public function update($vestorly-auth, $advisor_id, $id, $member) {

  		// parse inputs
  		$resourcePath = "api/advisors/{advisor_id}/members/{id}.json";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "PUT";
      $queryParams = array();
      $headerParams = array();
      $headerParams['Accept'] = '';
      $headerParams['Content-Type'] = '';

      // query params
      if($vestorly-auth != null) {
  		  $queryParams['vestorly-auth'] = $this->apiClient->toQueryValue($vestorly-auth);
  		}
      
      // path params
      if($advisor_id != null) {
  			$resourcePath = str_replace("{" . "advisor_id" . "}",
  			                            $this->apiClient->toPathValue($advisor_id), $resourcePath);
  		}// path params
      if($id != null) {
  			$resourcePath = str_replace("{" . "id" . "}",
  			                            $this->apiClient->toPathValue($id), $resourcePath);
  		}
      

  		// make the API Call
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);

      if(! $response) {
        return null;
      }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'void');
  		return $responseObject;
  }
  
	/**
	 * destroy
   *
	 * Deletes a member
   * vestorly-auth, string: Authentication token (required)
   * * advisor_id, string: Id of advisor (required)
   * * id, string: Id of member (required)
   * 
	 * @return void
	 */

   public function destroy($vestorly-auth, $advisor_id, $id) {

  		// parse inputs
  		$resourcePath = "api/advisors/{advisor_id}/members/{id}.json";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "DELETE";
      $queryParams = array();
      $headerParams = array();
      $headerParams['Accept'] = '';
      $headerParams['Content-Type'] = '';

      // query params
      if($vestorly-auth != null) {
  		  $queryParams['vestorly-auth'] = $this->apiClient->toQueryValue($vestorly-auth);
  		}
      
      // path params
      if($advisor_id != null) {
  			$resourcePath = str_replace("{" . "advisor_id" . "}",
  			                            $this->apiClient->toPathValue($advisor_id), $resourcePath);
  		}// path params
      if($id != null) {
  			$resourcePath = str_replace("{" . "id" . "}",
  			                            $this->apiClient->toPathValue($id), $resourcePath);
  		}
      

  		// make the API Call
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);

      if(! $response) {
        return null;
      }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'void');
  		return $responseObject;
  }
  

}
