#!/usr/bin/env python
"""
RssfeedsApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class RssfeedsApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def index(self, **kwargs):
        """Read a list of rss feed

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            ids, str: Return rss feed with list of IDs provided (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'ids']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method index" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/rss_feeds.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        
        if ('ids' in params):
            queryParams['ids'] = self.apiClient.toPathValue(params['ids'])
        

        

        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def create(self, **kwargs):
        """Create an post

        Args:
            
            rss_feed, str: JSON block of rss feed data (required)
            
            
        
        Returns: void
        """

        allParams = ['rss_feed']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method create" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/rss_feeds.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        

        

        

        
        if ('rss_feed' in params):
            formParams['rss_feed'] = params['rss_feed']
        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def show(self, **kwargs):
        """Retreive a single rss feed

        Args:
            
            vestorly-auth, str: Authentication token (required)
            
            
            id, str: Id of rss feed (required)
            
            
        
        Returns: void
        """

        allParams = ['vestorly-auth', 'id']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method show" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/rss_feeds/{id}.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        
        if ('vestorly-auth' in params):
            queryParams['vestorly-auth'] = self.apiClient.toPathValue(params['vestorly-auth'])
        

        

        
        if ('id' in params):
            replacement = str(self.apiClient.toPathValue(params['id']))
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def update(self, **kwargs):
        """Create an advisor

        Args:
            
            id, str: Id of post (required)
            
            
            rss_feed, str: JSON block of rss feed data (required)
            
            
        
        Returns: void
        """

        allParams = ['id', 'rss_feed']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method update" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/rss_feeds/{id}.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        

        

        
        if ('id' in params):
            replacement = str(self.apiClient.toPathValue(params['id']))
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        

        
        if ('rss_feed' in params):
            formParams['rss_feed'] = params['rss_feed']
        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    
    def destroy(self, **kwargs):
        """Destroy a post

        Args:
            
            id, str: Id of pow5 (required)
            
            
        
        Returns: void
        """

        allParams = ['id']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method destroy" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = 'api/rss_feeds/{id}.json'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = '';
        headerParams['Content-Type'] = '';

        

        

        
        if ('id' in params):
            replacement = str(self.apiClient.toPathValue(params['id']))
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject
        
        
        
    


