# coding: utf-8

"""
    Vestorly API

    Vestorly Developers API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TruncatedMember(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, first_name=None, last_name=None, email=None, picture_url=None, added_on=None):
        """
        TruncatedMember - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'first_name': 'str',
            'last_name': 'str',
            'email': 'str',
            'picture_url': 'str',
            'added_on': 'str'
        }

        self.attribute_map = {
            'id': '_id',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email',
            'picture_url': 'picture_url',
            'added_on': 'added_on'
        }

        self._id = id
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._picture_url = picture_url
        self._added_on = added_on

    @property
    def id(self):
        """
        Gets the id of this TruncatedMember.

        :return: The id of this TruncatedMember.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TruncatedMember.

        :param id: The id of this TruncatedMember.
        :type: str
        """

        self._id = id

    @property
    def first_name(self):
        """
        Gets the first_name of this TruncatedMember.

        :return: The first_name of this TruncatedMember.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this TruncatedMember.

        :param first_name: The first_name of this TruncatedMember.
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """
        Gets the last_name of this TruncatedMember.

        :return: The last_name of this TruncatedMember.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this TruncatedMember.

        :param last_name: The last_name of this TruncatedMember.
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """
        Gets the email of this TruncatedMember.

        :return: The email of this TruncatedMember.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this TruncatedMember.

        :param email: The email of this TruncatedMember.
        :type: str
        """

        self._email = email

    @property
    def picture_url(self):
        """
        Gets the picture_url of this TruncatedMember.

        :return: The picture_url of this TruncatedMember.
        :rtype: str
        """
        return self._picture_url

    @picture_url.setter
    def picture_url(self, picture_url):
        """
        Sets the picture_url of this TruncatedMember.

        :param picture_url: The picture_url of this TruncatedMember.
        :type: str
        """

        self._picture_url = picture_url

    @property
    def added_on(self):
        """
        Gets the added_on of this TruncatedMember.

        :return: The added_on of this TruncatedMember.
        :rtype: str
        """
        return self._added_on

    @added_on.setter
    def added_on(self, added_on):
        """
        Sets the added_on of this TruncatedMember.

        :param added_on: The added_on of this TruncatedMember.
        :type: str
        """

        self._added_on = added_on

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TruncatedMember):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
